replicasCount: 1
fullName: "hs-router"
selectorLabel: "hs-router"


service:
  nodePort: 30007
  httpPort: 8080

containers:
  router:
    name: router
    image: registry.alexstorm.solenopsys.org/alexstorm-hsm-router
    pullPolicy: Always
    httpPort: 8080
    httpHost: "0.0.0.0"
    servicesPorts: 9999
